- name: Install packages
  become: true
  package:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - binutils
    - make
    - htop
    - lib32gcc-s1

- shell: dpkg --add-architecture i386
  become: true

- name: Install amazon-efs-utils
  block:
  - name: Git clone efs-utils
    register: clone_status
    git:
      repo: https://github.com/aws/efs-utils.git
      dest: $HOME/efs-utils
      single_branch: yes
      version: master
  - name: "Shell: make deb"
    shell: cd $HOME/efs-utils && make deb
    when: clone_status.changed == true
  - name: Get files from $HOME/efs-utils/build/
    find:
      paths: $HOME/efs-utils/build/
      patterns: "*.deb"
      recurse: no
      file_type: file
    when: clone_status.changed == true
    register: found_deb
  - name: Install downloaded package
    become: true
    apt:
      update_cache: yes
      deb: "{{ found_deb.files[0].path }}"
    when: clone_status.changed == true

- block:
  - name: Create steam user
    become: true
    user:
        name: steam
        uid: 1730
        shell: /bin/bash
        create_home: true
        password: "1"
  - name: (Optional) Append cd /home/steam to .bashrc
    block: 
        - name: Test for line
          become: true
          shell: grep -c "^cd \$HOME" /home/steam/.bashrc || true
          register: test_grep
        - name: Add cd /home/steam if does not exists
          become: true
          lineinfile: 
              dest: /home/steam/.bashrc
              line: "cd $HOME"
          when: test_grep.stdout == "0"
  - name: Create directory /home/steam/.ssh
    become: true
    file:
      path: /home/steam/.ssh
      state: directory
      owner: steam
      group: steam
      mode: '0700'
  - name: Copy /home/admin/.ssh/authorized_keys
    become: true
    copy:
      src: /home/admin/.ssh/authorized_keys
      dest: /home/steam/.ssh/authorized_keys
      owner: steam
      group: steam
      mode: '0600'
      remote_src: true

- name: Check if mounted directory exists
  stat: 
    path: /mnt/{{ aws_conf.shared_efs_name}}
  register: sefs
- when: sefs.stat.exists == false
  block:
  - name: Create mounted directory
    become: true
    file:
      path: /mnt/{{ aws_conf.shared_efs_name}}
      state: directory
  - name: Grant access to steam user
    become: true
    file:
      dest: /mnt/{{ aws_conf.shared_efs_name}}
      owner: steam
      mode: u=rwX,g=rX,o=rX
  - name: Mount an NFS volume
    become: true
    mount:
      src: "{{ sharedEFSAddress }}"
      path: /mnt/{{ aws_conf.shared_efs_name}}
      opts: tls
      state: mounted
      fstype: efs
