- name: Install packages
  become: true
  package: 
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items: "{{ install_packages }}"
  tags: [ prepare-utils ]

- include: steam-user.yml
  tags: [ prepare-steam-user ]
