apiVersion: v1
kind: PersistentVolume
metadata:
  name: project1-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/maximov/git/act.io/infra/volume/project1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project1-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
