- name: Check that the steamcmd.sh exists
  stat: 
    path: $HOME/Steam/steamcmd.sh
  register: steamcmd_bin
- when: steamcmd_bin.stat.exists == false
  block: 
    - name: Create directory
      file: 
        path: "{{ item }}"
        state: directory
      with_items: 
        - $HOME/Steam
        - $HOME/.steam
        - $HOME/.steam/sdk32
    - name: Download steamcmd_linux.tar.gz
      unarchive: 
        src: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: $HOME/Steam
        remote_src: yes
    - name: "Shell: first run"
      shell: /bin/bash $HOME/Steam/steamcmd.sh +quit
    - name: Link the steamcmd executable
      file: 
        src: $HOME/Steam/linux32/steamclient.so
        dest: $HOME/.steam/sdk32/steamclient.so
        owner: steam
        state: link
