---
#- hosts: localhost
#  gather_facts: false
#  vars:
#    reqOwner: ""
#    reqName: ""
#  roles: [ infra ]

- hosts: "{{ reqOwner }}-{{ reqName }}"
  remote_user: ubuntu
  vars: 
    sharedEFSAddress: "{{ sefs_info.efs[0].filesystem_address | default('fs-00d7e48bcf9186570.efs.eu-central-1.amazonaws.com:/') }}"
  roles: [ cs2server ]
