- name: Retrieve volume info
  register: vol
  amazon.aws.ec2_vol_info: 
    filters: 
      "tag:Name": "{{ reqOwner }}-{{ reqName }}"
      "tag:isVolume": "True"

- name: Create volume
  when: vol.volumes | length == 0
  amazon.aws.ec2_vol: 
    device_name: "{{ aws_conf.vol_device_name }}"
    region: "{{ region }}"
    zone: "{{ region }}a"
    volume_size: "{{ aws_conf.vol_volume_size }}"
    tags: 
      region: "{{ region }}"
      reqName: "{{ reqName }}"
      reqOwner: "{{ reqOwner }}"
      Name: "{{ reqOwner }}-{{ reqName }}"
      isVolume: "True"

- name: Retrieve volume info
  register: vol
  amazon.aws.ec2_vol_info: 
    filters: 
      "tag:Name": "{{ reqOwner }}-{{ reqName }}"
      "tag:isVolume": "True"

- name: Volume output
  debug: msg="{{ vol }}"

- name: Attach volume
  amazon.aws.ec2_vol: 
    instance: "{{ ec2.instances[0].instance_id }}"
    id: "{{ vol.volumes[0].id }}"
