- name: Create EC2
  register: ec2
  amazon.aws.ec2_instance: 
      state: running
      region: "{{ region }}"
      name: "{{ reqOwner }}-{{ reqName }}"
      key_name: "{{ aws_conf.ssh_key }}"
      vpc_subnet_id: "{{ subnets_info.subnets[0].subnet_id }}"
      instance_type: "{{ aws_conf.ec2_instance_type }}"
      security_group: "{{ sg_info.security_groups[0].group_id }}"
      network: 
          assign_public_ip: true
      image_id: "{{ ec2_image }}"
      volumes: 
          - device_name: /dev/xvda
            ebs: 
                volume_size: 8
                volume_type: "{{ aws_conf.ec2_volume_type }}"
                delete_on_termination: true
      tags: 
          region: "{{ region }}"
          reqName: "{{ reqName }}"
          reqOwner: "{{ reqOwner }}"

- name: EC2 output
  debug: msg="{{ ec2.instances[0] }}"
